import PDFDocument from 'pdfkit/js/pdfkit.license.js';
import { storage } from '../appwrite/storage.js';
import { logger } from '../utils/logger.js';

const BUCKET_ID = 'reports';

export async function createReportPdf({ userId, researchData }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const title = researchData.title || `${researchData.symbol || 'Unknown'} — Research Report`;

      doc.fontSize(24).text(title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Generated by Guide Trade on ${new Date().toISOString()}`, { align: 'center' });
      doc.moveDown();

      doc.fontSize(14).text('Summary', { underline: true });
      doc.fontSize(11).text(researchData.summary || 'No summary available.');
      doc.moveDown();

      doc.fontSize(14).text('Bullish Factors', { underline: true });
      (researchData.bullishFactors || []).forEach((f, i) => {
        doc.fontSize(11).text(`${i + 1}. ${f}`);
      });
      doc.moveDown();

      doc.fontSize(14).text('Bearish Factors', { underline: true });
      (researchData.bearishFactors || []).forEach((f, i) => {
        doc.fontSize(11).text(`${i + 1}. ${f}`);
      });
      doc.moveDown();

      doc.fontSize(14).text('Key Risks', { underline: true });
      (researchData.risks || []).forEach((f, i) => {
        doc.fontSize(11).text(`${i + 1}. ${f}`);
      });
      doc.moveDown();

      doc.fontSize(14).text('Research-Based Outlook', { underline: true });
      doc.fontSize(11).text(researchData.outlook || 'See full report for details.');
      doc.moveDown();

      doc.fontSize(14).text('Sources', { underline: true });
      (researchData.sources || []).forEach((s, i) => {
        doc.fontSize(10).text(`${i + 1}. ${s.sourceTitle || s.sourceUrl || 'Unknown source'}`);
      });
      doc.moveDown();

      doc.fontSize(8).text(
        'Guide Trade provides research and educational information, not guaranteed financial predictions or personalized financial advice. Markets are uncertain and can move unexpectedly. Always verify information and consider your own risk tolerance.',
        { align: 'center' }
      );

      doc.end();
    } catch (err) {
      logger.error('PDF generation failed', { userId, error: err.message });
      reject(err);
    }
  });
}

export async function saveReport({ userId, researchId, title, fileBuffer }) {
  try {
    const fileName = `report_${researchId}_${Date.now()}.pdf`;
    const file = await storage.createFile(
      BUCKET_ID,
      fileName,
      fileBuffer,
      [`read("user:${userId}")`, `write("user:${userId}")`],
    );
    logger.info('Report saved', { userId, fileId: file.$id });
    return file;
  } catch (err) {
    logger.error('Report save failed', { userId, error: err.message });
    throw err;
  }
}

export async function getReportFile(userId, fileId) {
  return await storage.getFileDownload(BUCKET_ID, fileId);
}

export default { createReportPdf, saveReport, getReportFile, BUCKET_ID };
